### PR TITLE
Make sure the *Slice returned by it.Key() is freed

### LINKED ISSUE #59: Slice.Free()?
There's a `Free()` method on `Slice`.

There's little mention on this in the documentation, so I'm left wondering as to when/whether I should use it.

Intuitively I'd expect it to free the underlying resources in the native library.

Thus:

* If I don't call `Free()`, will this cause a memory leak?
* When is it safe to call `Free()`?
* There's this code:

```go
func (iter *Iterator) ValidForPrefix(prefix []byte) bool {
	return C.rocksdb_iter_valid(iter.c) != 0 && bytes.HasPrefix(iter.Key().Data(), prefix)
}
```

The result of `iter.Key()` is a `*Slice`, which is used but never freed here. Does that have a leak?

### PR DESCRIPTION
**Pull request by rubenv**
Fixes #59

### CODE REVIEW

**Comment by rubenv** [comment]
@tecbot Any chance you could have a look at this one?

The change is trivial but the effects are very significant.

**Comment by igm** [comment]
just to make the story complete #30

**Comment by igm** [comment]
Small test to demonstrate how Key slice is reused during iteration. It counts the number of unique Key.Data and Value.Data pointers. In my case it prints `1` for keys and `1048576` for values. I think this shows that key data slice is reused during iteration and does not need to be released. Also in case of using Free (line in the test needs to be uncommented) the result is the same, looks like Free has no effect (or if yes, even worse, the iterator keeps reusing the memory after being released)

```
func TestIteratorKeyMemoryLeak(t *testing.T) {
	db := newTestDB(t, "TestIteratorKeyMemoryLeak", nil)
	defer db.Close()

	wo := NewDefaultWriteOptions()
	for i := 0; i < 1<<20; i++ {
		ensure.Nil(t, db.Put(wo, []byte(fmt.Sprintf("key_%v", i)), []byte("some val")))
	}

	iter := db.NewIterator(NewDefaultReadOptions())
	keyPointers := map[uintptr]bool{}
	valPointers := map[uintptr]bool{}
	for iter.SeekToFirst(); iter.Valid(); iter.Next() {
		key := iter.Key()
		keyData := key.Data()
		val := iter.Value().Data()
		kH := (*reflect.SliceHeader)(unsafe.Pointer(&keyData))
		vH := (*reflect.SliceHeader)(unsafe.Pointer(&val))
		keyPointers[kH.Data] = true
		valPointers[vH.Data] = true
//		key.Free()
	}
	iter.Close()
	fmt.Println(len(keyPointers), len(valPointers))
}
```

**Comment by igm** [comment]
I guess this is probably my last comment on this, I think that calling Free() is not needed, see comment here:
https://github.com/facebook/rocksdb/blob/master/table/internal_iterator.h#L55:L59
The iterator manages Slice internally.

Whereas Get(...) is quite different story. There is a memory allocation that needs to be freed and is implemented in C wrapper:
https://github.com/facebook/rocksdb/blob/master/db/c.cc#L723
and
https://github.com/facebook/rocksdb/blob/master/db/c.cc#L401:L405

**Comment by rubenv** [comment]
I can test again if desired.

Then again, this doesn't hurt either, does it?

Feel free to revert it, but when things aren't broken, why are we touching them?

**Pull request merged**
