### PR TITLE
Second approach to fix null termination issue

### PR DESCRIPTION
**Pull request by cv711**

### CODE REVIEW

**Comment by cv711** [comment]
@tecbot @JelteF @xiaogaozi thoughts?

**Comment by xiaogaozi** [comment]
Great implementation! Looks good to me.

**Comment by JelteF** [comment]
This seems very racey if two things are registered at the same time their indexes might not be the same for both lists. This can be solved easily by putting a wrapper struct with both values in a single cowlist.

**Comment by cv711** [comment]
@JelteF I agree, latest commit does just that

**Comment by JelteF** [comment]
LGTM then, I don't have merge rights though. And I haven't seen @tecbot respond to issues/PRs in a while. So I'm not sure when this will be merged.

**Pull request merged**
